---
title: "Example_map"
author: "LM"
date: "10/5/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Some very helpful resources for learning how to put these things together:

Geocomputation with R by Robin Lovelace https://bookdown.org/robinlovelace/geocompr/

sf Cheat Sheet https://github.com/rstudio/cheatsheets/blob/master/sf.pdf 

Sean Hardison's sf workshop https://github.com/seanhardison1/sf-workshop 
 
ggplot2 from the masters themselves
https://ggplot2-book.org/index.html 

The R Graph Gallery
https://www.r-graph-gallery.com/index.html 



```{r Load packages}
library(tidyverse) # always (includes ggplot2)
library(readr) # read in datasets
library(maps) # a package full of data. This is where I will pull land masses from
library(sf) # simple features. A great package for handling spatial data
```

```{r}
#Data


# Extract land mass from maps package
states <- map_data("state")
NEUS <- subset(states, region %in% c("Maine", "massachusetts", "new hampshire", "vermont", "maine", "rhode island",
                "connecticut","new york","new jersey","delaware","pennsylvania",
                            "maryland","virginia","north carolina","west virginia"))
```

```{r}
# statistical areas

#from https://www.fisheries.noaa.gov/resources/maps
#more datasets here: ftp://ftp.nefsc.noaa.gov/pub/gis/ (doesn't open in Chrome)  
areas <- st_read(dsn = "./Statistical_Areas_2010_withNames") %>%
  st_set_crs(4269) # set coordinate reference system

#choosing the statistical areas in our region
areas <- areas %>% filter(Id %in% c("464", "465", "511", "512", "513", "514", "515", "521", "522", "525", "526", "537", "538", "539", "551", "561", "562", "611", "612", "613"))  

#finding the center of each of those statistical area polygons so we can put a label there later
centroids <- sf::st_coordinates(st_centroid(areas)) 
areas <- cbind(areas, centroids)
```

```{r}
#NEFSC Bottom Trawl Survey https://oceanadapt.rutgers.edu/
survey <- read.csv("./NEFSC_bottom_trawl_data.csv")
 
# I'm just making some subsets here for simplicity, instead of dealing with the whole dataset
cod <- survey %>% filter(Species == "Gadus morhua")
sandlance <- survey %>% filter(Species == "Ammodytes dubius")
herring <- survey %>% filter(Species == "Clupea harengus")
somefish <- filter(survey, Species %in% c("Gadus morhua", "Ammodytes dubius", "Clupea harengus"))


```


```{r}

#make plot
ggplot() +   
 
#get rid of the grid lines, but keep the lat/long markers
   theme_classic() +  
  
# plot data as points
 geom_point(data = somefish, aes(y = Latitude, x = Longitude, colour = Species)) +
  
 #add land mass
  geom_polygon(data = NEUS, aes(x=long, y = lat, group = group), fill = "darkgreen",  color="black",inherit.aes = FALSE)  +
  
  #add statistical area outlines
   geom_sf(data = areas, color = "black", size = 0.5, alpha =0) +
  
  # label statistical areas
   geom_text(data = areas, aes(x = X, y = Y, label = Id, face = "bold"), color = "white", size = 2) +
  
# title your plot  
  ggtitle("Mapping the NEFSC Bottom Trawl Survey") +

 # crop your map
  coord_sf(ylim = c(40, 44),  xlim = c(-74, -67))
```

